{% set name = "cnv-vcf2json" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cnv_vcf2json-{{ version }}.tar.gz
  sha256: 7a1fc7bde137e7d2dc766aeda21b446373c32129af1d5259304dae24b5f857e5

build:
  entry_points:
    - cnv-vcf2json = vcf_converter.cnv_vcf2json:cnv_vcf2json
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - jsonschema

test:
  imports:
    - vcf_converter
  commands:
    - pip check
    - cnv-vcf2json --help
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Converts the CNVkit structural variants VCF file into JSON format
  license: CC-BY-NC-4.0
  home: https://pypi.org/project/cnv-vcf2json/

extra:
  recipe-maintainers:
    - khaled196
